author:
  email: contact@renewablepowerinsight.com
  name: Energy AI Team
baseurl: /RenewablePowerInsight
description: AI-powered insights into renewable energy trends and developments
excerpt_separator: <!--more-->
highlighter: rouge
markdown: kramdown
paginate: 10
paginate_path: /page:num/
permalink: /:year/:month/:day/:title/
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
show_excerpts: true
social:
  github: kweiss51
  twitter: renewablepower
theme: minima
title: Renewable Power Insight
url: https://kweiss51.github.io
