title: Renewable Power Insight
description: Comprehensive insights into renewable energy trends and developments
baseurl: "/RenewablePowerInsight"
url: "https://kweiss51.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
permalink: /:year/:month/:day/:title/

# Jekyll plugins (GitHub Pages supported only)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Excerpt settings
excerpt_separator: <!--more-->
show_excerpts: true

# Author info
author:
  name: Energy Research Team
  email: contact@renewablepowerinsight.com

# Social links
social:
  github: kweiss51
  twitter: renewablepower
